language: scala
jdk:
  - openjdk8
scala:
  - 2.12.10
script:
  - git tag 0.1234.5678
  - sbt -sbt-launch-repo https://repo1.maven.org/maven2 clean coverage test coverageAggregate
  - git tag -d 0.1234.5678
after_success: sbt coveralls
