version: "3.1"

services:
  conseil-postgres:
    image: postgres:10.3-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: "conseiluser"
      POSTGRES_PASSWORD: "p@ssw0rd"
      POSTGRES_DB: "conseil-local"
    volumes:
    - "./pgdata:/var/lib/postgresql/data"
    - "./doc/conseil.sql:/docker-entrypoint-initdb.d/conseil.sql"
