version: "3.1"

services:
  conseil-api:
    image: cryptonomictech/conseil:latest
    ports:
      - 80:80
    environment:
      #  List of supported environment variables:
      #  DBHOST=${DB_Host:=db}
      #  DBUSER=${DB_User:=user}
      #  DBPW=${DB_Password:=password}
      #  DBDB=${DB_Database:=conseil}
      #  DBPORT=${DB_Port:=5432}
      #  XTZSCHEME=${XTZ_Scheme:=http}
      #  XTZHOST=${XTZ_Host:=node}
      #  XTZPREFIX=${XTZ_Prefix:=}
      #  XTZPORT=${XTZ_Port:=8732}
      #  XTZPLATFORM=${XTZ_Platform:=tezos}
      #  XTZNET=${XTZ_Network:=mainnet}
      #  APIPORT=${API_PORT:=80}
      #  APIKEY=${API_KEY:=conseil}
      DB_Host: conseil-postgres
      DB_User: conseiluser
      DB_Password: p@ssw0rd
      DB_Database: conseil-local
      DB_Port: 5432
      XTZ_Scheme: https
      XTZ_Host: tezos-staging.cryptonomic-infra.tech
      XTZ_Port: 443
      XTX_Platform: tezos
      XTZ_Network: mainnet
    entrypoint: ["/root/wait-for.sh", "conseil-postgres:5432", "-t", "120", "--", "/root/entrypoint.sh", "conseil-api"]
    volumes:
      - "conseil-sql:/root/sql/"
    networks:
      - conseil-net

  conseil-lorre:
    image: cryptonomictech/conseil:latest
    environment:
      DB_Host: conseil-postgres
      DB_User: conseiluser
      DB_Password: p@ssw0rd
      DB_Database: conseil-local
      DB_Port: 5432
      XTZ_Scheme: https
      XTZ_Host: tezos-staging.cryptonomic-infra.tech
      XTZ_Port: 443
      XTX_Platform: tezos
      XTZ_Network: mainnet
    command: conseil-lorre
    depends_on:
      - conseil-postgres
    networks:
      - conseil-net

  conseil-postgres:
    image: postgres:11.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "conseiluser"
      POSTGRES_PASSWORD: "p@ssw0rd"
      POSTGRES_DB: "conseil-local"
      POSTGRES_INITDB_ARGS: "--lc-collate=en_US.UTF-8 -E UTF8"
    volumes:
      - "conseil-sql:/docker-entrypoint-initdb.d/"
    networks:
      - conseil-net

volumes:
  conseil-sql:

networks:
  conseil-net:
    driver: bridge
