version: "3.1"

services:
  conseil-api:
    image: cons:latest
    ports:
      - 80:80
    environment:
      # List of supported environment variables:

      # CONSEIL_XTZ_NETWORK:???           # (default zeronet)
      # CONSEIL_XTZ_ENABLED:???           # (default false)
      # CONSEIL_XTZ_NODE_PROTOCOL:???     # (default https)
      # CONSEIL_XTZ_NODE_HOSTNAME:???     # (default nautilus.cryptonomic.tech)
      # CONSEIL_XTZ_NODE_PORT:???         # (default 8732)
      # CONSEIL_XTZ_NODE_PATH_PREFIX:???  # (default tezos/zeronet/)
      # CONSEIL_XTZ_BACKER_ROLLS_SIZE:??? # (default 8000)

      # CONSEIL_BTC_NETWORK:???                           # (default mainnet)
      # CONSEIL_BTC_ENABLED:???                           # (default false)
      # CONSEIL_BTC_NODE_PROTOCOL:???                     # (default https)
      # CONSEIL_BTC_NODE_HOSTNAME:???                     # (default localhost)
      # CONSEIL_BTC_NODE_PORT:???                         # (default 8332)
      # CONSEIL_BTC_NODE_USERNAME:???                     # (default bitcoin)
      # CONSEIL_BTC_NODE_PASSWORD:???                     # (default sP9PV88xtbGwLMAEi2rVlZ7jIFfJbpOmTUCsBBBRN9I=)
      # CONSEIL_BTC_BATCHING_INDEXER_THREADS_COUNT:???    # (default 8)
      # CONSEIL_BTC_BATCHING_HTTP_FETCH_THREADS_COUNT:??? # (default 8)
      # CONSEIL_BTC_BATCHING_HASH_BATCH_SIZE:???          # (default 2000)
      # CONSEIL_BTC_BATCHING_BLOCKS_BATCH_SIZE:???        # (default 500)
      # CONSEIL_BTC_BATCHING_TRANSACTIONS_BATCH_SIZE:???  # (default 500)

      # CONSEIL_ETH_NETWORK # (default mainnet)
      # CONSEIL_ETH_ENABLED # (default false)

      # CONSEIL_QUO_NETWORK # (default mainnet)
      # CONSEIL_QUO_ENABLED # (default false)

      # CONSEIL_API_DB_NAME:???     # (default conseil)
      # CONSEIL_API_DB_USER:???     # (default foo)
      # CONSEIL_API_DB_PASSWORD:??? # (default bar)
      # CONSEIL_API_DB_URL:???      # (default jdbc:postgresql://localhost:5432/postgres)

      # CONSEIL_API_HOSTNAME:???         # (default 0.0.0.0)
      # CONSEIL_API_PORT:???             # (default 1337)
      # CONSEIL_API_KEY:???              # (required)
      # CONSEIL_API_ALLOW_BLANK_KEYS:??? # (default false)

      # CONSEIL_NC_ENABLED: ???          # (default false)
      # CONSEIL_NC_HOST: ???             # (default http://localhost)
      # CONSEIL_NC_PORT: ???             # (default 1234)
      # CONSEIL_NC_PATH: ???             # (default apiKeys/dev)
      # CONSEIL_NC_KEY: ???              # (default exampleApiKeyDev)

      # JVM_XMX:??? # (recommended -Xmx4G)

      # CONFIG_PATH:??? # (optional path to external configuration)

      CONSEIL_XTZ_DB_URL: "jdbc:postgresql://conseil-postgres:5432/conseil-local"
      CONSEIL_XTZ_DB_USER: "conseiluser"
      CONSEIL_XTZ_DB_PASSWORD: "p@ssw0rd"
      CONSEIL_XTZ_PORT: 80
      CONSEIL_XTZ_KEY: "conseil"

      CONSEIL_API_ALLOW_BLANK_KEYS: "true"

      CONSEIL_XTZ_NETWORK: "granadanet"
      CONSEIL_XTZ_ENABLED: "true"
      CONSEIL_XTZ_NODE_HOSTNAME: "tezos-granada.cryptonomic-infra.tech"
      CONSEIL_XTZ_NODE_PORT: 443

      JVM_XMX: "4G"
    entrypoint: ["/root/wait-for.sh", "conseil-postgres:5432", "-t", "120", "--", "/root/entrypoint.sh", "conseil-api"]
    depends_on:
      - conseil-postgres
    volumes:
      - "conseil-sql:/root/sql/"
    networks:
      - conseil-net

  conseil-lorre:
    image: cons:latest
    environment:
      # List of supported environment variables:

      # CONSEIL_XTZ_NETWORK:???           # (default zeronet)
      # CONSEIL_XTZ_ENABLED:???           # (default false)
      # CONSEIL_XTZ_NODE_PROTOCOL:???     # (default https)
      # CONSEIL_XTZ_NODE_HOSTNAME:???     # (default nautilus.cryptonomic.tech)
      # CONSEIL_XTZ_NODE_PORT:???         # (default 8732)
      # CONSEIL_XTZ_NODE_PATH_PREFIX:???  # (default tezos/zeronet/)
      # CONSEIL_XTZ_BACKER_ROLLS_SIZE:??? # (default 8000)

      # CONSEIL_BTC_NETWORK:??? # (default mainnet)
      # CONSEIL_BTC_ENABLED:??? # (default false)

      # CONSEIL_XTZ_DB_NAME:???     # (default conseil) - similarly for ETH, BTC, but replace XTZ with it
      # CONSEIL_XTZ_DB_USER:???     # (default foo)
      # CONSEIL_XTZ_DB_PASSWORD:??? # (default bar)
      # CONSEIL_XTZ_DB_URL:???      # (default jdbc:postgresql://localhost:5432/postgres)

      # CONSEIL_LORRE_FORK_DETECTION_ENABLED:true/false # (default false)

      # JVM_XMX:??? # (recommended -Xmx4G)

      # CONFIG_PATH:??? # (optional path to external configuration)

      # LORRE_RUNNER_PLATFORM:??? (required - name of platform to be executed by lorre)
      # LORRE_RUNNER_NETWORK:???  (required - name of network to be executed by lorre, note that network needs to be enabled)

      CONSEIL_XTZ_DB_URL: "jdbc:postgresql://conseil-postgres:5432/conseil-local"
      CONSEIL_XTZ_DB_USER: "conseiluser"
      CONSEIL_XTZ_DB_PASSWORD: "p@ssw0rd"

      CONSEIL_LORRE_DEPTH: "newest"
      CONSEIL_LORRE_HEAD_HASH: "head"

      CONSEIL_XTZ_NETWORK: "granadanet"
      CONSEIL_XTZ_ENABLED: "true"
      CONSEIL_XTZ_NODE_HOSTNAME: "tezos-granada.cryptonomic-infra.tech"
      CONSEIL_XTZ_NODE_PORT: 443

      LORRE_RUNNER_PLATFORM: "tezos"
      LORRE_RUNNER_NETWORK: "granadanet"

      CONSEIL_LORRE_DEPTH: 1320
      CONSEIL_LORRE_HEAD_HASH: "BMGvXZT9xqJeNNvEupHNLppwbmqnQR4sgd9XHyDWn818MBQDC27"

      # Feature-Flag: set to false to disable the concurrent computation of future endorsement/baking rights
      CONSEIL_LORRE_BLOCK_RIGHTS_FETCHING_ENABLED: "true"

      JVM_XMX: "4G"
    entrypoint: ["/root/wait-for.sh", "conseil-postgres:5432", "-t", "120", "--", "/root/entrypoint.sh", "conseil-lorre"]
    depends_on:
      - conseil-postgres
    networks:
      - conseil-net

  conseil-postgres:
    image: postgres:11.9
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "conseiluser"
      POSTGRES_PASSWORD: "p@ssw0rd"
      POSTGRES_DB: "conseil-local"
      POSTGRES_INITDB_ARGS: "--lc-collate=en_US.UTF-8 -E UTF8"
    volumes:
      - "conseil-sql:/docker-entrypoint-initdb.d/"
    networks:
      - conseil-net

volumes:
  conseil-sql:

networks:
  conseil-net:
    driver: bridge
